export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SUBMIT_CART = 'SUBMIT_CART';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
